#ifndef VERSION_H
#define VERSION_H

#define _SNK_DEV_BUILD		1				//SET TO 0 ON RELEASE COMMIT

#define _SNK_MAJ_VERSION	2				//UPDATE THIS DEFINE ON VERSION CHANGE
#define _SNK_MIN_VERSION	3				//UPDATE THIS DEFINE ON VERSION CHANGE

#define __STRINGIFY(x)		#x
#define _STRINGIFY(x)		__STRINGIFY(x)

#if _SNK_DEV_BUILD==1
#define SNK_STR_VERSION 	_STRINGIFY(_SNK_MAJ_VERSION._SNK_MIN_VERSION) "-dev"
#else
#define SNK_STR_VERSION 	_STRINGIFY(_SNK_MAJ_VERSION._SNK_MIN_VERSION)
#endif
#define SNK_VSVI_VERSION	_SNK_MAJ_VERSION,_SNK_MIN_VERSION,0,0
#define SNK_CRIGHT_YEARS	"2012-2017"		//UPDATE THIS DEFINE ON VERSION CHANGE

#endif //VERSION_H
